classDiagram
  Class01 <|-- AveryLongClass : extends
  Class03 *-- Class04 : composition
  Class05 o-- Class06 : aggregation
  Class07 --> Class08 : association
  Class09 ..> Class10 : dependency
  Class11 --() Class12 : lollipop
