flowchart TD
    A@{ shape: manual-input, label: "Manual Input" }
    B@{ shape: document, label: "Document" }
    C@{ shape: display, label: "Display" }
    D@{ shape: internal-storage, label: "Internal Storage" }
    E@{ shape: manual, label: "Manual Operation" }

    A --> B --> C --> D --> E
