flowchart LR
  User[User] --> Logo
  Logo@{ img: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADUlEQVR42mP8z8BQDwAE/wH+Y9ycGQAAAABJRU5ErkJggg==", label: "Brand", pos: "b", w: 64, h: 64 }
  Logo --> End[Done]
